### ISSUE TITLE
Return errors from `Dlerror()`

### ISSUE THREAD

**Issue by Arsen6331** [ebitengine/purego#100]
It would be better if `Dlerror()` returned errors, rather than strings as it does now. That would allow users to check errors using a nil check, rather than an empty string check, as well as allow them to return an error from `purego` as an `error` type from their own function. It would also provide the ability to wrap `purego` errors, such as with `%w` in `fmt.Errorf()`, as well as with the new functions added in Go 1.20, such as `errors.Join()`.

`Dlerror()` could simply use `errors.New()` to create a new error with the given string, but I feel it would be even better to define a custom error type that just returns a string. That way, the type information tells the caller that the error came from `purego`.

This would look something like:

```go
type Error struct {
	s string
}

func (e Error) Error() string {
	return e.s
}
```

If this seems like a good idea, I could submit a PR to implement it.

**Comment by hajimehoshi** [comment]
This would be a breaking change but it should be allowed since this is still v0.

I'm fine with returning an error from Dlerror, but @TotallyGamerJet what do you think?

**Comment by TotallyGamerJet** [comment]
I think returning an error is a good idea. However, Go normally returns the error with the value that could fail. So shouldn't Dlopen and Dlsym return an error with its value? And Dlerror be removed/deprecated? That would have some overhead since it'd be calling two functions instead of one but is likely worth it for the more idiomatic api.

**Comment by hajimehoshi** [comment]
> I think returning an error is a good idea. However, Go normally returns the error with the value that could fail. So shouldn't Dlopen and Dlsym return an error with its value? And Dlerror be removed/deprecated? That would have some overhead since it'd be calling two functions instead of one but is likely worth it for the more idiomatic api.

I prefer this idea. We don't have to keep the low-level API as it is, as purego's concept is not to provide the libdl API as it is.
