### ISSUE TITLE
Is it possible to Dlopen an embed shared object?

### ISSUE THREAD

**Issue by Xuanwo** [ebitengine/purego#102]
Golang has native `embed` support since golang 1.16.

```go
import "embed"

//go:embed hello.txt
var f embed.FS
data, _ := f.ReadFile("hello.txt")
print(string(data))
```

Is it possible to `Dlopen` a shared object within embed fs? This way we can distribute binaries more easily.

**Comment by TotallyGamerJet** [comment]
Currently no. The cross platform way is to write the embedded file to a temporary directory and then dlopen that. View our discussion [here](https://github.com/hajimehoshi/ebiten/pull/2367) about what we are trying for ebitengine.

**Comment by Xuanwo** [comment]
Thank you for the clarification! Do I need to keep this issue open to prevent others who may have the same question?

**Comment by TotallyGamerJet** [comment]
@hajimehoshi Should this be closed?

**Comment by hajimehoshi** [comment]
As long as we don't have an actual plan to do this, we should close this.
