### ISSUE TITLE
SSE instruction segfaults fakecgo init

### ISSUE THREAD

**Issue by eliottness** [ebitengine/purego#106]
Some SSE instructions have requirements that make the fakecgo package segfault. In my case, the call to `malloc` during `x_cgo_init` in [`internal/fakecgo/go_linux_amd64.go`](https://github.com/ebitengine/purego/blob/main/internal/fakecgo/go_linux_amd64.go#L81) makes use of a [`movaps`](https://c9x.me/x86/html/file_module_x86_id_180.html) instruction on `0x10(%rsp)`. But since `%rsp` was not aligned on 16 bits (as the instruction requires it), the cgo initialization segfaults. Fixing the register manually using gdb does the trick but of course it messes with the stack and segfault laters.

My team and I are really fond and the project and really want it to work on linux so I will probably drop a PR if I find a fix in the following days. If you have a definitive idea on how to fix this or if you want more debug information, please let me know.

**Comment by TotallyGamerJet** [comment]
Aligning the stack should be pretty easy. Something like`ANDQ $-16, SP`. However, I don't understand how the SSE instructions are calling into fakecgo. If you provide a MRE I can experiment with a solution as well. It would also be useful to add as a test.

**Comment by TotallyGamerJet** [comment]
@eliottness and @klauspost does my branch [fix-106](https://github.com/TotallyGamerJet/purego/tree/fix-106) solve this?

**Comment by eliottness** [comment]
> @eliottness and @\klauspost does my branch [fix-106](https://github.com/TotallyGamerJet/purego/tree/fix-106) solve this?
@TotallyGamerJet Yes it does for me. Do you still want the MRE I was doing ? This was basically me creating a fake `libc.so.6` with something like this:

```c
void *malloc(size_t size)
{
    asm("movaps %rsp, %xmm0");
    return NULL;
}
```

Then running:
```sh
LD_LIBRARY_PATH="$PWD:$LB_LIBRARY_PATH" go test
```

Not sure how it would integrate with the current testsuite through.

**Comment by TotallyGamerJet** [comment]
It's not possible to use Cgo in go test. Forcing CGO_ENABLED=0 in the GitHub tests should be enough if it has a similar malloc implementation

**Comment by eliottness** [comment]
Indeed you are right. I have [this action](https://github.com/eliottness/purego/actions/runs/4461043945) failing on [this commit](https://github.com/eliottness/purego/commit/a99a3bfc0dd357f71ae8f90b45f2515a3a50aa6b), but [this action](https://github.com/eliottness/purego/actions/runs/4461064440) is fine with [this commit](https://github.com/eliottness/purego/commit/a6a6e398a09574ecec0eaf59177914f4480a1a9f). Go ahead and merge what you please. Thanks again for the fix.
