### ISSUE TITLE
How to new NSString

### ISSUE THREAD

**Issue by anhoder** [ebitengine/purego#113]
Is there an example of how to create an NSString variable

**Comment by TotallyGamerJet** [comment]
The name at the top is the selector and shouldn't broken up. So it would be something like: `Send(objc.RegisterName("initWithBytes:length:encoding:"), b, len(b), 4)`.

You can look at Oto or Ebitengine to see more examples of how to use this package.

**Comment by TotallyGamerJet** [comment]
Also, using fmt.Println with the objc.ID won't print out the string since it's just a pointer. If that was your intent.

**Comment by anhoder** [comment]
> The name at the top is the selector and shouldn't broken up. So it would be something like: `center.Send(objc.RegisterName("initWithBytes:length:encoding:"), b, len(b), 4)`.
> 
> You can look at Oto or Ebitengine to see more examples of how to use this package.

It ran successfully, thank you!

**Comment by anhoder** [comment]
> Also, using fmt.Println with the objc.ID won't print out the string since it's just a pointer. If that was your intent.

Yeah. I just want to confirm that the return result is not 0
