### ISSUE TITLE
Support for static initialization dlopen/dlsym calls

### ISSUE THREAD

**Issue by eliottness** [ebitengine/purego#118]
Hello,

I noticed that in [`dlopen`](https://github.com/ebitengine/purego/blob/main/dlfcn.go#L37) and [`dlsym`](https://github.com/ebitengine/purego/blob/ebd8567e49db0b4514b146f222a59dd1acd618b7/dlfcn.go#L49) in `dlfcn.go` , the return value is never checked against nil. Is there a reason for this ? This blocks the use of any call to dlopen or any similar function in the static initialization of the library loaded. In the end, if the inner call fails, the dlerror value set by the inner call would make the top call fail.

Do tell me if you need more precisions or if you want me to do a PR or an MRE.

**Comment by TotallyGamerJet** [comment]
I'm not sure I understand. Dlerror returns a string representing the error if any. If none then the empty string is returned from it. That is why in Dlopen it checks for the empty string. If not empty it wraps it in an error type. Are you asking why doesn't it look like `if err :=dlerror(); err != nil {}`? 

Unless your saying that when you Dlopen a library that also Dlopen's another library that isn't there so Dlerror is set. However, it didn't check the value so our Dlopen successes to open the library but will have an error. If that is the case it's an error in the other library for not checking errors. What should purego do differently?

**Comment by eliottness** [comment]
> Unless your saying that when you Dlopen a library that also Dlopen's another library that isn't there so Dlerror is set.

This is exactly as you mentioned. A shared library is loaded and the static initialization triggers during the first call to dlopen, which nest a second call to dlopen in the first one. We do not check for dlerror in this second call because it is ok for it to fail silently. Here is the flow of actions:

* Dlopen("lib1.so") (go)
  * dlopen("lib1.so") (c)
  * Loads the library, no errors
  * Set dlerror value to an empty string
  * do static init
    * dlopen("lib2.so")
    * fails silently and set dlerror value
    * finish static init normally
  * return the handle (not null)
* Dlopen checks for dlerror value, returns 0, dlerror()

I feel that it is easily fixable by modifying Dlopen:
```go
func Dlopen(path string, mode int) (uintptr, error) {
	u := fnDlopen(path, mode)
	if errStr := fnDlerror(); errStr != "" {
		return 0, Dlerror{errStr}
	}
	return u, nil
}
```

to this:
```go
func Dlopen(path string, mode int) (uintptr, error) {
	u := fnDlopen(path, mode)
	if u == 0 {
		return 0, Dlerror{fnDlerror()}
	}
	return u, nil
}
```

Because I feel that, in the first place, the way Dlopen should check if there is error is to check if the handle returned is null. The call to dlerror should only be done if the handle returned it null. Am I missing something @TotallyGamerJet ?

**Comment by TotallyGamerJet** [comment]
So the [Posix API](https://pubs.opengroup.org/onlinepubs/009696799/functions/dlopen.html) guarantees that Dlopen will return NULL if an error occurs.

> If file cannot be found, cannot be opened for reading, is not of an appropriate object format for processing by dlopen(), or if an error occurs during the process of loading file or relocating its symbolic references, dlopen() shall return NULL. More detailed diagnostic information shall be available through dlerror().

That means it's safe to check for NULL first before getting the error like you suggested. Since its safe it might be worth changing since it's not required to get the error since it is only for _more_ information. I'm leaning towards making the change. @hajimehoshi do you think it should be changed?

**Comment by TotallyGamerJet** [comment]
@eliottness If you want to make a PR you can or I can do it
