### ISSUE TITLE
Implement fakecgo

### ISSUE THREAD

**Issue by TotallyGamerJet** [ebitengine/purego#12]
This issue tracks the implementation of fakecgo which is needed for some frameworks to function properly when CGO_ENABLED=0. It will be similar to [notti/nocgo](https://github.com/notti/nocgo/tree/master/internal/fakecgo)

**Comment by TotallyGamerJet** [comment]
The next step for this issue is to either implement it for iOS and/or linux

**Comment by hajimehoshi** [comment]
It's up to you which way you go with :-)

I think porting GLFW is another big issue.

**Comment by TotallyGamerJet** [comment]
I'll probably port the rest of Ebitengine which includes internal/ui/ui_glfw_darwin.go and internal/gamepad/gamepad_darwin.go before attempting GLFW.

**Comment by hajimehoshi** [comment]
Sure!

**Comment by TotallyGamerJet** [comment]
So I think this can be closed as fakecgo is implemented on Linux and macOS. @hajimehoshi agree?

**Comment by hajimehoshi** [comment]
Yes!
