### ISSUE TITLE
Mac Callback

### ISSUE THREAD

**Issue by leaanthony** [ebitengine/purego#129]
Hi there!

I'm trying to hook into Apple's GCD method `dispatch_async` to schedule callbacks on the main thread. I've gotten pretty far but the final call never returns. 

The obj-c code I'm trying to replace is:

```objective-c
	dispatch_async(dispatch_get_main_queue(), ^{
		// some code
	});
```

I discovered that `dispatch_get_main_queue` is actually a macro and returns the address of `_dispatch_main_q`. 
The following is where I'm up to. It feels like I'm missing just one final piece:

```go
func dispatchTest() {
	libSystem, err := purego.Dlopen("libSystem.dylib", purego.RTLD_NOW|purego.RTLD_GLOBAL)
	if err != nil {
		panic(err)
	}
	dispatchMainQueue, err := purego.Dlsym(libSystem, "_dispatch_main_q")
	if err != nil {
		panic(err)
	}
	var dispatch_async func(uintptr, uintptr)
	goFunc := func() {
		fmt.Println("Hello from the main thread")
	}
	callback := purego.NewCallback(goFunc)
	purego.RegisterLibFunc(&dispatch_async, libSystem, "dispatch_async")
	dispatch_async(dispatchMainQueue, callback)
	println("i never get here")
}

func main() {

	// Since the error wasn't checked before check it before calling any code.
	NSApp := NewNSSharedApplication()
	go func() {
		time.Sleep(1 * time.Second)
		dispatchTest()
	}()
	NSApp.Run()
}
```
The NSApp code is just the same as from last ticket so left out to simplify the example.
Nothing is crashing or suggesting anything bad is happening. Am I using `NewCallback` correctly? My guess is that it's to do with C vs Obj-C calling conventions...

Any help appreciated! 

chip: Apple M2 Pro
macOS: 13.2.1 (22D68)

**Comment by TotallyGamerJet** [comment]
So it does crash on my system (M1 Max, 13.3.1).

From my research I've discovered that blocks are not the same thing as a normal C function pointer despite the fact that it's header definition would [like you to believe so](https://developer.apple.com/documentation/dispatch/dispatch_block_t). My suspicions were raised by this [gist](https://gist.github.com/vc7/11361908). See [Block_private.h](https://opensource.apple.com/source/libclosure/libclosure-59/Block_private.h.auto.html) which shows that its implementation is an ObjC object. Now there are no public nor private methods for creating a Block struct that I can find. So I don't think it's a good idea to attempt to create one of these. Here's an article about its [implementation](https://www.cocoawithlove.com/2009/10/how-blocks-are-implemented-and.html). I'd recommend choosing a different approach. One perhaps where you intercept the main run loop and use go channels to pass the Go callback and run it on the main thread. I think ebitengine does something similar using [glfw](https://github.com/glfw/glfw/blob/master/src/cocoa_init.m)

**Comment by leaanthony** [comment]
Thanks for taking the time to respond to this 🙏 I'll look at how to get the main loop running in Go and pump Cocoa's event loop 👍

**Comment by TotallyGamerJet** [comment]
@leaanthony Hey! So I came across DarwinKit and it appears they support blocks. Looking at the code it appears to also be possible to do with purego. I hope this helps! https://github.com/progrium/macdriver/blob/main/objc/block.go

**Comment by TotallyGamerJet** [comment]
This gist is basically replacing each call to C with one using purego

**Comment by leaanthony** [comment]
The linked source code appears to use CGO? Maybe I'm missing something?

**Comment by TotallyGamerJet** [comment]
Yes replace the calls to Cgo with purego calls to those same functions

**Comment by hajimehoshi** [comment]
I'd like to use dispatch_data_create, and this requries a block. In the current situation, we should create a block by ourselves reffering https://github.com/progrium/macdriver/blob/main/objc/block.go, right?

**Comment by TotallyGamerJet** [comment]
> I'd like to use dispatch_data_create, and this requries a block. In the current situation, we should create a block by ourselves reffering https://github.com/progrium/macdriver/blob/main/objc/block.go, right?

Yes refer to that code on how to implement a dispatch block.

**Comment by leaanthony** [comment]
Amazing! If you get a basic example working, please share! 🙏

**Comment by hajimehoshi** [comment]
In my use case, passing 0 (NULL) to a block argument was enough, so I realized I didn't have to port that...
