### ISSUE TITLE
examples/libc: doesn't work on Windows

### ISSUE THREAD

**Issue by vault-thirteen** [ebitengine/purego#130]
Is Windows O.S. support planned ?

**Comment by TotallyGamerJet** [comment]
What are looking to do? Syscall and NewCallback is already supported.

**Comment by vault-thirteen** [comment]
> What are looking to do? Syscall and NewCallback is already supported.

The Readme fila states that this library is `for calling C functions from Go without Cgo`.

**Comment by hajimehoshi** [comment]
https://pkg.go.dev/github.com/ebitengine/purego?GOOS=windows

It's already supported as @TotallyGamerJet said.

**Comment by vault-thirteen** [comment]
```
func getSystemLibrary() string {
	switch runtime.GOOS {
	case "darwin":
		return "/usr/lib/libSystem.B.dylib"
	case "linux":
		return "libc.so.6"
	default:
		panic(fmt.Errorf("GOOS=%s is not supported", runtime.GOOS))
	}
}
```

If I run your code on Windows, I will get an error.

**Comment by hajimehoshi** [comment]
@TotallyGamerJet Would it be feasible to make the `libc` example support Windows?

**Comment by hajimehoshi** [comment]
If not, we might have to have another example for Windows.

**Comment by TotallyGamerJet** [comment]
Dlopen is not supported on windows so you'd use LoadLibrary. I don't think there is a way to use that in the example. This is similar to what was brought up in #107. Maybe another example would be best

**Comment by hajimehoshi** [comment]
I think separating the `Dlopen` part to another file like `main_unix.go` might work but I am not sure what's the DLL name for libc on Windows.

**Comment by vault-thirteen** [comment]
AFAIK, Windows O.S. uses `kernel32.dll` and `user32.dll` instead of C library.
