### ISSUE TITLE
Question: strategy for determining file names

### ISSUE THREAD

**Issue by leaanthony** [ebitengine/purego#133]
On Linux, the name of the file is needed to open it. A recent test failed on one machine as the installed library had a suffix of ".0". What is the guidance on determining filenames on Linux so that they can be opened? Many thanks 🙏

**Comment by TotallyGamerJet** [comment]
Well normally you expect the version to be specified by being included in the name. Like libc.so.6 or something. Is the expected shared object named differently on other distributions? And which specific library are you trying to load?

**Comment by leaanthony** [comment]
Thanks for the reply. So in this instance we have a program that uses the following code:

```go
	gtk, err = purego.Dlopen("libgtk-3.so", purego.RTLD_NOW|purego.RTLD_GLOBAL)
```

Which appears to work on some distributions, but on Ubuntu 23.04 (ARM) it didn't - it just errored out saying `libgtk-3.so` was not found. After a search, I did find that I had `libgtk-3.so.0` though. Based on what you are saying about the dynamic linker, it should have found this right?

**Comment by TotallyGamerJet** [comment]
I have confirmed that on my arm64 Ubuntu 20.04.2 libgtk is called `libgtk-3.so.0`. According to the [GTK docs](https://docs.gtk.org/gtk3/compiling.html), it appears the proper way to get the name of the library is to use `pkg-config --cflags gtk+-3.0` hello.c -o hello `pkg-config --libs gtk+-3.0`. Perhaps you can use the -X linker flag to set a string with the proper name. If that doesn't work I'm not sure what will.

**Comment by leaanthony** [comment]
I think it may be a case of having a few variations to try and running pkg-config if they fail
