### ISSUE TITLE
can not use from windows

### ISSUE THREAD

**Issue by calvin2021y** [ebitengine/purego#136]
I use `v0.4.0-alpha.4` for windows, the `openLibrary` from example is not public.

Is there a unite public library load method ?

**Comment by TotallyGamerJet** [comment]
The recommended solution is to copy the implementation of openLibrary for windows in the example. 

See #107 for an explanation as to why there is no cross platform version of Dlopen provided by purego

**Comment by calvin2021y** [comment]
thanks for the tips. one more question about the windows:

```txt
RegisterFunc takes a pointer to a Go function representing the calling convention of the C function.
```

this mean `RegisterFunc` only accept `extern "C" `  calling convention, right ?

**Comment by TotallyGamerJet** [comment]
Yes purego can only call C ABI functions.
