### ISSUE TITLE
thread local storage not work

### ISSUE THREAD

**Issue by calvin2021y** [ebitengine/purego#137]
when link the dynamic library by cgo (without purego), thread local storage  work fine.

when use purego load the  dynamic library,  thread local storage return 0 at first visit, then return value before assign from other os thread.

confirm the problem from linux, windows, macOS.  (go1.20.5)

**Comment by calvin2021y** [comment]
This cloud related with bring the https://github.com/timandy/routine from purego test. I will do more to confirm.

**Comment by calvin2021y** [comment]
the problem is cause by this code:

```go
//go:linkname gopark runtime.gopark
func gopark(unlockf func(uintptr, unsafe.Pointer) bool, lock unsafe.Pointer, reason uint8, traceEv byte, traceskip int)

gopark(nil, nil, 0, 0, 1)
```

I use gopark to do the goroutine yield(for late call goready to wakeup).

If there is more than 5K goroutine yield,  then TLS stop working.  (I am not even start call goready TLS already break)

If less than 5K,  then it work as expect.

**Comment by calvin2021y** [comment]
test to trigger this:

```go
package main

import "C"
import (
	"fmt"
	"github.com/ebitengine/purego"
	"runtime"
	"time"
	"unsafe"
)

//go:linkname gopark runtime.gopark
func gopark(unlockf func(uintptr, unsafe.Pointer) bool, lock unsafe.Pointer, reason uint8, traceEv byte, traceskip int)

func main() {

	lib1, err := purego.Dlopen("printTls.dylib", purego.RTLD_NOW|purego.RTLD_GLOBAL)
	if err != nil {
		panic(err)
	}
	var printTls func(v1 uintptr, d uint32)
	purego.RegisterLibFunc(&printTls, uintptr(lib1), "printTls")

	go func() {
		for {
			time.Sleep(10 * time.Millisecond)
			printTls(0, 211)
		}
	}()

	var max uintptr = 1024 * 8
	var show_at uintptr = 211

	var i uintptr
	for i = 0; i < max; i++ {
		go func(i uintptr) {
			if i%show_at == 0 {
				fmt.Printf("inside %v\n", i)
			}
			gopark(nil, nil, 0, 0, 1)
		}(i)
	}

	time.Sleep(1000 * time.Millisecond)
}
````

printTls just some simple code to use tls and print it.

If remove `fmt.Printf("inside %v\n", i)`, then the bug not triggered. 

TLS show wrong var some time correct some time not.

**Comment by hajimehoshi** [comment]
I think you need to use [`runtime.LockOSThread`](https://pkg.go.dev/runtime#LockOSThread) to use TLS correctly on a groutine.

**Comment by calvin2021y** [comment]
the tls only used from c and not related into go.  to create a object for each os thread.  (I am not sure how to free this object yet, maybe some code like on_thread_exit)

I will do more test to confirm

**Comment by calvin2021y** [comment]
yes.

I will call from a random go thread,  which run inside a go random go `M` or `P`,  it will do it work inside c world.

**Comment by calvin2021y** [comment]
I guess this should be my code bugs, not related into purego.  I will do more test to confirm

**Comment by calvin2021y** [comment]
should be my code problem
