### ISSUE TITLE
enable `RegisterClass` for a struct with member variables

### ISSUE THREAD

**Issue by hajimehoshi** [ebitengine/purego#143]
Now `RegisterClass` is available only for structs without member variables. If a struct had member variables, memory corruption might happen (`examples/objc` uses `RegisterClass` for a struct with a member variable, but this is a known issue).

As @TotallyGamerJet and Hajime discussed on Ebitengine Discord, would it be possible giving up mirroring member variables in the Go world to the Objective-C world? This makes the Objective-C struct size predictable and then memory corruption would no longer happen. Unfortunately, this would be a breaking change since `GetIvar` and `SetIvar` no longer works for Go member variables. However, the current major version is still 0, Hajime is fine to have such a breaking change.

Currently, a struct with members can use `AllocateClassPair`, `AddMethod`, and `AddIvar`, but this is quite painful. `RegisterClass` cares all of them, which is pretty nice.

**Comment by hajimehoshi** [comment]
Currently, class member variables (ivars) in Objective-C are automatically defined from struct member variables in Go.

As we discussed in Discord, I suggest:

* Don't define member variables (ivars) for Objective-C.
* Define accessors (a getter and/or a setter) for Go member variables if a user specifies a struct tag (e.g. `objc:"@getter,@setter"`)

And now, I am waiting for @TotallyGamerJet's proposals :-)

**Comment by TotallyGamerJet** [comment]
The proposal can be found [here](https://docs.google.com/document/d/1PBe0uzph-5K7FesMbJUpPJJFvAsYSe9Hwuquk90ufi4/edit?usp=sharing).

**Comment by hajimehoshi** [comment]
Nice! Can we have a permission to add comments?

**Comment by hajimehoshi** [comment]
> `func RegisterClass(object ClassDef, definitions []MethodDef) (Class, error)`

Hmm? Who can define a type implementing `ClassDef`? `ClassDef` has an unexported member, right?

> `objc:"@property (readwrite)"`

* For a member `FooBar`, `objc` defines a getter `fooBar` and `setFooBar`, right?
* For a boolean member, is `is` used for getters?

**Comment by TotallyGamerJet** [comment]
It should be possible to add comments now

**Comment by TotallyGamerJet** [comment]
> Hmm? Who can define a type implementing `ClassDef`? `ClassDef` has an unexported member, right?


That's the idea. The only way to create a struct that implements ClassDef is by embedding ObjC.Class. It's a little compiler safety instead of just any.

> * For a member `FooBar`, `objc` defines a getter `fooBar` and `setFooBar`, right?
Yes if it has `@property` tag.

> * For a boolean member, is `is` used for getters?

Does ObjC do that? Otherwise you can set the getter name with the property attribute

**Comment by hajimehoshi** [comment]
> The proposal can be found [here](https://docs.google.com/document/d/1PBe0uzph-5K7FesMbJUpPJJFvAsYSe9Hwuquk90ufi4/edit?usp=sharing).

We have reached the agreement, right?

**Comment by TotallyGamerJet** [comment]
Yes we did. I've implemented most of it. Just trying to do the attributes methods. Then the PR will be created

**Comment by hajimehoshi** [comment]
This was reverted due to an issue.
