### ISSUE TITLE
Bazel build of purego failing

### ISSUE THREAD

**Issue by eliottness** [ebitengine/purego#144]
Bazel does not use the go usual build process for an increase in building speed. For this, they use their usual sandbox which makes the current working directory a random temporary directory and not the current package. This makes cross-package `#include` unable to work since the included file is not at the right place at build time. Here is the error:

```
external/com_github_ebitengine_purego/internal/fakecgo/asm_arm64.s:7: 
#include: open /var/folders/fn/j3_08pb94p9_hyz4myff84br0000gq/T/abi/abi_arm64.h: no such file or directory
compilepkg: error running subcommand external/go_sdk/pkg/tool/darwin_arm64/asm: exit status 1
```

The files where it fails are the following:
* [`internal/fakecgo/asm_amd64.h`](https://github.com/ebitengine/purego/blob/b178e7518254895d38a88b4bcdbc02cda4221263/internal/fakecgo/asm_amd64.s#L6)
* [`internal/fakecgo/asm_arm64.h`](https://github.com/ebitengine/purego/blob/b178e7518254895d38a88b4bcdbc02cda4221263/internal/fakecgo/asm_arm64.s#L6)
* [`sys_amd64.h`](https://github.com/ebitengine/purego/blob/b178e7518254895d38a88b4bcdbc02cda4221263/sys_amd64.s#L7C1-L7C1)
* [`sys_arm64.h`](https://github.com/ebitengine/purego/blob/b178e7518254895d38a88b4bcdbc02cda4221263/sys_arm64.s#L7C1-L7C1)

Purego is especially useful in Bazel environments because CGO is disabled by default. I checked on bazel side and this behaviour seems unavoidable. Do we know if cross-package usage of `#include` is really something that is officially supported (in which case bazel is at fault) and not a happy coincidence ? It is only a matter of copying the files in `purego/internal/abi` to `purego/internal/fakecgo` and `purego/`, in which case I can do the PR, or am I missing something ?

**Comment by hajimehoshi** [comment]
Which Go version are you using?

**Comment by eliottness** [comment]
> Which Go version are you using?
@hajimehoshi 1.20.5

**Comment by TotallyGamerJet** [comment]
The assembler is poorly documented so if it's "officially" supported is mostly implementation defined. It's probably best to create an issue with Bazel to see if they'll fix it. Otherwise, I'm not sure how I feel about the copying since that would duplicate the abi headers.

**Comment by hajimehoshi** [comment]
> `func RegisterClass(object ClassDef, definitions []MethodDef) (Class, error)`

Hmm? Who can define a type implementing `ClassDef`? `ClassDef` has an unexported member, right?

> `objc:"@property (readwrite)"`

* For a member `FooBar`, `objc` defines a getter `fooBar` and `setFooBar`, right?
* For a boolean member, is `is` used for getters?

**Comment by eliottness** [comment]
I finally had the time to push this, we will see how they respond 👍

**Comment by eliottness** [comment]
I looked into the project since the issues does not seems to be taken care of. And it seems that I will be really hard to make this work because each package is compiled in a separate sandbox. This would mean adding a `-I ...` argument for each package of the module which might as well surpass the maximum number of argument you can pass to a program for huge modules. And this is not taking into account the fact that we would need to bring the data about the whole module very deeply into somewhere it should not be in the first place.

@TotallyGamerJet I understand your concerns about copying the files and if I had any other working option I would present it to you but purego is a tool we intended to use on bazel in the first place, so it's a must on our side. Is there room for discussion ?

**Comment by eliottness** [comment]
If the issue is about duplicating some code that was already copied from elsewhere, then we could build a small markdown table somewhere to reference all the files copied and where they come from. Just like you did in the README but more elaborate

**Comment by TotallyGamerJet** [comment]
My concern was that if upstream Go changes the files than we have to remember to update it in all locations. However, I don't know any other solution and it's important to have bazel working

**Comment by eliottness** [comment]
We could create a job scheduled every X than would git clone and diff the files. Just we could find the dev build stream and try to run purego regularly on it.

**Comment by TotallyGamerJet** [comment]
That seems a little over-engineered for 4 files that don't change every release. I say we just copy them for now. You can make that PR if you want or wait until later for me to do it.
