### ISSUE TITLE
Crash after upgrading to Go 1.21

### ISSUE THREAD

**Issue by JackMordaunt** [ebitengine/purego#152]
I'm working on an app that uses `oto` to play sound. It crashes on my M1 (ARM) Mac.  
I'm sorry for the lack of detail, let me know what data I can collect to make this more helpful. 

`oto v2.4.0`
`purego v0.3.0`

```
panic: runtime error: index out of range [220994744] with length 2000

goroutine 354 [running, locked to thread]:
github.com/ebitengine/purego.callbackWrap(0x342dfd9a0)
	/Users/jmordaunt/go/pkg/mod/github.com/ebitengine/purego@v0.3.0/syscall_sysv.go:134 +0x60f
```

**Comment by hajimehoshi** [comment]
Could you give me a minimal code to reproduce this issue? Thanks,

**Comment by JackMordaunt** [comment]
Oh I should say the Go toolchain I'm using is Go 1.21 and it looks like there are [fixes](https://github.com/ebitengine/purego/commit/26d1789b9e6a34cefab6065ad5fec073ab83666b) for 1.21

**Comment by hajimehoshi** [comment]
OK so case closed.

**Comment by JackMordaunt** [comment]
Yeah I just reverted my toolchain to 1.20 and I have no panic. Thanks!

**Comment by hajimehoshi** [comment]
Wait, so this happens with Go 1.21? What about the latest version of Oto (v3) and purego (v0.4.0)?

**Comment by JackMordaunt** [comment]
Let me upgrade to `oto v3` and I'll get back to you asap :)

**Comment by hajimehoshi** [comment]
Note that v3 is `github.com/ebitengine/oto/v3`, not `https://github.com/hajimehoshi/oto/v3`. Thanks,

**Comment by JackMordaunt** [comment]
> Note that v3 is `github.com/ebitengine/oto/v3`, not `github.com/hajimehoshi/oto/v3`. Thanks,

Haha yeah, that just confused me a bit. After upgrading and compiling with 1.21 I observe no crash. 

So this appears to be only a problem when upgrading to 1.21 while using older versions of oto. 

We can close this ticket, thanks @hajimehoshi!

**Comment by hajimehoshi** [comment]
Thank you for confirming this!
