### ISSUE TITLE
 How to receive uint8_t * in golang

### ISSUE THREAD

**Issue by Cyberhan123** [ebitengine/purego#164]
The C code is
```c++
uint8_t * function img(){
  std::vector<uint8_t> result;
  static auto *data = (uint8_t *) result.data();
  return data;
}
```
 How to receive `uint8_t *` in golang
 
By the way, it is actually a picture. I feel that the mapping in golang is `[]byte`

**Comment by TotallyGamerJet** [comment]
Please review the [docs](https://pkg.go.dev/github.com/ebitengine/purego?GOOS=darwin#RegisterFunc) for `RegisterFunc`. A `uint8_t *` would be `*uint8` or `*byte`. You can then make it a slice if you know the size using `unsafe.Slice(data, dataSize)`

**Comment by TotallyGamerJet** [comment]
Closing as this is not an issue. Future questions can be directed to the [Discord](https://discord.com/channels/842049801528016967/1123106378731487345).

**Comment by Cyberhan123** [comment]
Thanks for your help.
