### ISSUE TITLE
Float return Values dont work

### ISSUE THREAD

**Issue by JupiterRider** [ebitengine/purego#176]
This one always returns zero:
```golang
var getFrameTime func() float32
purego.RegisterLibFunc(&getFrameTime, raylibDll, "GetFrameTime")
delta := getFrameTime()
// delta is 0
```

When using the syscall package like this, it works:
```golang
getFrameTime, _ := syscall.GetProcAddress(handle, "GetFrameTime")
_, ret, _ := syscall.SyscallN(getFrameTime)
delta := *(*float32)(unsafe.Pointer(&ret))
// delta is 0.0166667
```

**Comment by TotallyGamerJet** [comment]
Yeah I noticed & fixed this when working on struct support. The fix is probably worth merging now instead of waiting for my struct PR to be complete.

**Comment by JupiterRider** [comment]
Thank you very much! :)

**Comment by TotallyGamerJet** [comment]
Also, fyi there is a safer way to convert the bit representation to a float using [math.Float32frombits](https://pkg.go.dev/math#Float32frombits) and it's 64bit equivalent.

**Comment by JupiterRider** [comment]
> Also, fyi there is a safer way to convert the bit representation to a float using [math.Float32frombits](https://pkg.go.dev/math#Float32frombits) and it's 64bit equivalent.

Ah ok. So you mean, when converting from uintptr to float?

**Comment by TotallyGamerJet** [comment]
> Ah ok. So you mean, when converting from uintptr to float?

Yes. In your second example instead of using unsafe you could've just done:

```go
math.Float32frombits(ret)
```

**Comment by hajimehoshi** [comment]
The test fails on 0.5. I'll rever the cherry-pick once.

https://github.com/ebitengine/purego/actions/runs/6915374716/job/18814228166

**Comment by TotallyGamerJet** [comment]
It seems to be because 0.5 doesn't have #63 which added callbacks on Linux which the float tests need.

**Comment by hajimehoshi** [comment]
> You can tell because the other callback tests are skipped.

Sure!

**Comment by hajimehoshi** [comment]
Done: 930b6648e1294aae39e60c46b48e971ca4e4bf1a

**Comment by TotallyGamerJet** [comment]
Hmm but on second though maybe not. There doesn't seem to be any changes to the code. Just documentation and changes to the testing.
