### ISSUE TITLE
Can I now build kernel modules in Go?

### ISSUE THREAD

**Issue by shehackedyou** [ebitengine/purego#188]
I have been trying to figure out a way to build kernel modules in Go and have been hitting a wall over and over. With Libc do you think i can call in linux headers to make the module? Or would more things have to be created first for that to work. 

It would make a fantastic example case for teaching people to use the project and how powerful it is if it is possible like I think it is.

**Comment by TotallyGamerJet** [comment]
I do not know much about how Linux kernel modules work. However, this project is solely focused on calling system shared object files in userspace.

You may find some of my other repos helpful. They customize the building process of go to run it in obscure environments. Such as the Limine one.

**Comment by shehackedyou** [comment]
So this is just to access system calls previously only available going through libc?

I really appreciate your answer, it filled in a lot of details for me. Because I want to understand this better it seems like a useful tool.

**Comment by TotallyGamerJet** [comment]
It can call any C function so you could use it for creating guis or games. Which is what it is used for in Ebitengine.

**Comment by shehackedyou** [comment]
Realized it would also make hacking games like counter-strike in purego now should be a lot easier. Kernel modules are a special kind of SO, soo Ill get familiar with the code.
