### ISSUE TITLE
ObjC runtime tests hit SIGBUS with go 1.22rc1

### ISSUE THREAD

**Issue by RomainMuller** [ebitengine/purego#193]
Hey!

As seen in #191, the `objc_runtime_darwin_test.go` tests appear to crash with `go 1.22rc1`.
I haven't been able to diagnose exactly what causes this issue just yet (and also am not entirely sure where to start from).

Since go1.22 is expected to release some time in February, it is probably a good idea to investigate this and address the problem.

**Comment by TotallyGamerJet** [comment]
I'll look into it

**Comment by RomainMuller** [comment]
I've also not been able to reproduce the problem on my machine (macOS 14.2.1 / ARM M1 Max), which I find a little weird.

**Comment by TotallyGamerJet** [comment]
The GitHub tests run on amd64. Did you run the test with GOARCH=amd64?

**Comment by TotallyGamerJet** [comment]
The issue only happens on amd64 and when CGO_ENABLED=1

**Comment by TotallyGamerJet** [comment]
I found the offending commit in [golang/go#36ecff0](https://github.com/golang/go/commit/bc15070085ec417d4254f8a4eda62b42de88fb37). This commit removed the NOFRAME attribute from `crosscall2`. Doing the same in `internal/cgo/asm_amd64.s` produces the same error. I need to investigate to see if there is a workaround for purego but it may be best to create an issue in golang.

**Comment by hajimehoshi** [comment]
Unfortunately the fix didn't work on 0.5.

**Comment by hajimehoshi** [comment]
We decided not to backport the fix to 0.5. Instead, we will release 0.6 earlier.
