### ISSUE TITLE
Support returning struct

### ISSUE THREAD

**Issue by TotallyGamerJet** [ebitengine/purego#195]
Similar to #88 but about returning structs.

**Comment by shehackedyou** [comment]
I believe this can currently be done by wrapping the struct with a function that returns that type of struct; but I agree, this would be useful. 

I have a list of programs I want to update once I understand this library better.

**Comment by pushkarmoi** [comment]
@shehackedyou @TotallyGamerJet is there a way to achieve this? Any code sample would be very helpful.
Lets say i want to use the following C function definition - 

```
typedef struct BytesBuffer {
  int32_t length;
  uint8_t *start;
} BytesBuffer;

struct BytesBuffer get_field_value(int64_t handle, char *key, int32_t key_len;
```

**Comment by TotallyGamerJet** [comment]
> @shehackedyou @TotallyGamerJet is there a way to achieve this? Any code sample would be very helpful.

It can be done but it's not yet implemented in purego which is the reason for this issue.

**Comment by irootyou** [comment]
omg, i cant beleive i missed this, thank you so much!
