### ISSUE TITLE
question about OpenCL

### ISSUE THREAD

**Issue by MatejMagat305** [ebitengine/purego#215]
I am only asking, could be theoretically possible use purego to opencl.so?
And , could be theoretically possible use purego on android f. e. to opencl.so?
as https://github.com/krrishnarraj/libopencl-stub ...., 
and last question is:  could it accept `int` to `typedef int  cl_GLint;` or `cl_int`?

**Comment by TotallyGamerJet** [comment]
> I am only asking, could be theoretically possible use purego to opencl.so?

Yes, it can open any .so

> And , could be theoretically possible use purego on android f. e. to opencl.so?
> as https://github.com/krrishnarraj/libopencl-stub ...., 

Most likely but it isn't actively tested. Android is just Linux after all

> and last question is:  could it accept `int` to `typedef int  cl_GLint;` or `cl_int`?

Go's `int` is most likely bigger than C's `int` so it's not correct. You probably want this:

```go
type GLint int32
```

Making sure the sizes are the same is important and purego can't verify that it's correct.

Also, for future questions please post in the Discord linked in the README

**Comment by MatejMagat305** [comment]
> > I am only asking, could be theoretically possible use purego to opencl.so?
> 
> Yes, it can open any .so
> 
> > And , could be theoretically possible use purego on android f. e. to opencl.so?
> > as https://github.com/krrishnarraj/libopencl-stub ....,
> 
> Most likely but it isn't actively tested. Android is just Linux after all
> 
> > and last question is:  could it accept `int` to `typedef int  cl_GLint;` or `cl_int`?
> 
> Go's `int` is most likely bigger than C's `int` so it's not correct. You probably want this:
> 
> ```go
> type GLint int32
> ```
> 
> Making sure the sizes are the same is important and purego can't verify that it's correct.
> 
> Also, for future questions please post in the Discord linked in the README

thank, I am sorry, but discord seems like that:
![discord](https://github.com/ebitengine/purego/assets/61238240/b6f7ed05-b542-4f82-a234-ea880b90e76a)
