### ISSUE TITLE
objc: `_IMP` is not exported though this is used in exported functions

### ISSUE THREAD

**Issue by hajimehoshi** [ebitengine/purego#22]
I think we should rename `_IMP` to an exported one. @TotallyGamerJet what do you think?

**Comment by hajimehoshi** [comment]
```
// _IMP is unexported so that the only way to make this type is by providing a Go function and casting
// it with the IMP function
```

OK so this is intentional, but this is not Go-conventional.

**Comment by TotallyGamerJet** [comment]
I don't think there is any other way that a user would need or want to create an IMP other than providing a go function to the IMP function. Can you think of one?

Plus doing it this way ensures that the function follows IMP convention (self objc.ID, _cmd objc.SEL)

**Comment by hajimehoshi** [comment]
https://pkg.go.dev/github.com/ebitengine/purego@v0.0.0-20220816145426-8dbe340b03f1/objc#example-IMP

So as a returning value from `IMP` is a function pointer and is used at `SyscallN` (and `AddMethod`), what if having `IMP` return `uintptr` instead of `_IMP`?

> Plus doing it this way ensures that the function follows IMP convention

I don't understand this point.

**Comment by TotallyGamerJet** [comment]
> I  don't understand this point.

An IMP is not just any normal callback. According to the [Apple Docs](https://developer.apple.com/documentation/objectivec/objective-c_runtime/imp) IMP must have the signature:

 `id (*IMP)(id, SEL, ...)`.

`purego.IMP` checks to make sure the function being passed has this signature.

The only reason to have _IMP be an exported type is to allow users to create variables of it. But where would they get the C function pointers from? I can only think of `purego.Dlsym` but even so the `objc.IMP` function will do the proper casting for you see [objc/objc_runtime_darwin.go](https://github.com/ebitengine/purego/blob/8dbe340b03f11115e843b9ee32252727985fb822/objc/objc_runtime_darwin.go#L230). Perhaps we just make the casting part of the API instead of an internal thing. That way if they _somehow_ get a C pointer and want to use it in `AddMethod` then they can pass it to `purego.IMP` and get an `_IMP`.

As for `purego.SyscallN`, I don't think that's going to be a common way to call an _IMP. It would be safer to use `ID.Send`.

**Comment by hajimehoshi** [comment]
> As for purego.SyscallN, I don't think that's going to be a common way to call an _IMP. It would be safer to use ID.Send.

I saw this usage in the example: https://pkg.go.dev/github.com/ebitengine/purego@v0.0.0-20220816145426-8dbe340b03f1/objc#example-IMP

So assuming `_IMP` + `Syscall` usage is rare, what about having `AddMethod` accept `interface{}` instead of `_IMP`, and getting a uintptr for it internally?

**Comment by TotallyGamerJet** [comment]
I wrote that example as a test to make sure SyscallN functions properly. Not necessarily as a common usage of either IMP or SyscallN. If we did that would we then export `_IMP` and remove `objc.IMP()`?

**Comment by TotallyGamerJet** [comment]
However, it is sometimes useful to have an IMP to send to an object. Also [NSObject.method(for:)](https://developer.apple.com/documentation/objectivec/nsobject/1418863-method) returns an IMP so perhaps there should be an exported type

**Comment by hajimehoshi** [comment]
> I wrote that example as a test to make sure SyscallN functions properly. Not necessarily as a common usage of either IMP or SyscallN. If we did that would we then export _IMP and remove objc.IMP()?

I don't suggest removing `IMP` function. Do you think we might have only either `IMP` and `_IMP`?

So, I suggest

1. Let `IMP()` return `uintptr`
2. Let `IMP()` return a new type `IMPType` or something
3. Rename `IMP()` to `NewIMP()` or something and `_IMP` to `IMP`

1. is the simplest and this was my previous suggestion (https://github.com/ebitengine/purego/issues/22#issuecomment-1220872343). What do you think?

**Comment by TotallyGamerJet** [comment]
I've now come around to the idea of making the type exported. I think suggestion 3 is the best move because it can still be important to specify that the callback is an IMP and not just any callback which uintptr could be. Also `NewIMP()` is still descriptive of what the function does.

**Comment by hajimehoshi** [comment]
Acknowledged. I'm fine with the idea 3. (NewIMP). I'll create a PR tomorrow or later, or you can make a PR and I'm happy to review :-)

**Comment by TotallyGamerJet** [comment]
You can make the PR

**Comment by hajimehoshi** [comment]
I thought we reached the agreement with 3: 

> Rename IMP() to NewIMP() or something and _IMP to IMP

But I'd like to confirm your idea at the PR: https://github.com/ebitengine/purego/pull/23#discussion_r950728447 Could you elraborate this?

**Comment by TotallyGamerJet** [comment]
I am agreeing that `IMP()` become `NewIMP()` and `_IMP` become `IMP`. My comment was about if we should make the casting of uintptr to IMP be a part of the exported API. I think that portion can be removed since it will now be possible to cast uintptr to IMP. `IMP(C.someFunc)`

**Comment by hajimehoshi** [comment]
Are you suggesting to remove these lines?

```go
	if x, ok := fn.(uintptr); ok {
		return IMP(x)
	}
```

**Comment by TotallyGamerJet** [comment]
Yes
