### ISSUE TITLE
purego 1.22.1 segfault

### ISSUE THREAD

**Issue by martinarisk** [ebitengine/purego#231]
Purego is used for libxkbcommon.so in the web browser:

 https://github.com/neurlang/wayland/tree/master/go-wayland-browser/browser

$ go version
go version go1.22.1 linux/amd64
$ ./browser 
Segmentation fault (core dumped)

RUN go version
 ---> Running in 4024fa28b11d
go version go1.21.6 linux/amd64

working

**Comment by martinarisk** [comment]
Additional info from valgrind

==99208== Invalid read of size 8
==99208==    at 0x4546F2: runtime.sigtrampgo (signal_unix.go:476)
==99208==  Address 0x50 is not stack'd, malloc'd or (recently) free'd

**Comment by TotallyGamerJet** [comment]
The project has purego 0.5.2 in the go.mod. Please update to at least 0.7.1 and see if that fixes the issue. If that does not fix it I need a minimally reproducible version that just uses purego. I will not debug your project for you.

**Comment by martinarisk** [comment]
Thanks, when bumped version of purego to v0.7.1, it works.
