### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by YatoGaml** [ebitengine/purego#238]
### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] Android
- [ ] iOS

### What feature would you like to be added?

Hi there! 
I managed to find you thanks to your steam account. Can we have a chat?

### Why is this needed?

Just here to get in touch with u

**Comment by TotallyGamerJet** [comment]
Use the discord for communication purposes
