### ISSUE TITLE
Does this project support LuaJIT, and if so, which versions of LuaJIT are compatible?

### ISSUE THREAD

**Issue by vela-security** [ebitengine/purego#241]
### Operating System

- [X] Windows
- [X] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] Android
- [ ] iOS

### What feature would you like to be added?

Does this project support LuaJIT, and if so, which versions of LuaJIT are compatible?

**Comment by TotallyGamerJet** [comment]
Yes it should. Any version of LuaJIT should work since the C ABI has not changed.

**Comment by TotallyGamerJet** [comment]
@vela-security Has your question been answered so this can be closed?

**Comment by TotallyGamerJet** [comment]
Closing as there hasn't been a response.
