### ISSUE TITLE
Filing a new issue has broken link to GitHub Discussions

### ISSUE THREAD

**Issue by dominikh** [ebitengine/purego#243]
### PureGo Version

-

### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] Android
- [ ] iOS

### Go Version (`go version`)

-

### What steps will reproduce the problem?

When filing a new issue, one is prompted to choose a template, or to
> use one of the forums for questions or general discussions

That last choice includes a button that opens https://github.com/ebitengine/purego/discussions, but Discussions don't seem to be enabled for this repository, and thus the link 404s.

### What is the expected result?

-

### What happens instead?

-

**Comment by hajimehoshi** [comment]
Isn't this working now?

**Comment by dominikh** [comment]
Yes, discussions have been enabled since I filed this issue.
