### ISSUE TITLE
purego callback function unsupport string ?

### ISSUE THREAD

**Issue by vela-security** [ebitengine/purego#246]
### Operating System

- [X] Windows
- [X] macOS
- [X] Linux
- [X] FreeBSD
- [X] Android
- [ ] iOS

### What feature would you like to be added?

not supporting string will increase a lot of development costs

**Comment by JupiterRider** [comment]
Hey @vela-security ,
you can use a byte pointer and convert this one into a string uxing the windows / unix package. Here is an example:
```golang
func traceLogCallbackWrapper(fn TraceLogCallbackFun) uintptr {
	return purego.NewCallback(func(logLevel int32, text *byte) uintptr {
		fn(int(logLevel), windows.BytePtrToString(text))
		return 0
	})
}
```
Source: https://github.com/gen2brain/raylib-go/blob/raylib/v5.0.0/raylib/purego_windows.go#L39

**Comment by vela-security** [comment]
good ths..

**Comment by TotallyGamerJet** [comment]
> not supporting string will increase a lot of development costs

I don't fully understand. Increasing development costs is usually a bad thing. 

Forcing callbacks to be platform dependent because they take a string argument isn't the greatest user experience
