### ISSUE TITLE
purego.Dlopen fails on Galaxy A02s

### ISSUE THREAD

**Issue by hajimehoshi** [ebitengine/purego#262]
### PureGo Version

v0.8.0-alpha.3

### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [X] Android
- [ ] iOS

### Go Version (`go version`)

go version go1.22.5 darwin/arm64

### What steps will reproduce the problem?

Call `purego.Dlopen("libGLESv2.so", purego.RTLD_LAZY|purego.RTLD_GLOBAL)` on Android

### What is the expected result?

An so file is loaded

### What happens instead?

Error:

```
invalid flags to dlopen: 101
```

### Anything else you feel useful to add?

[Galaxy A02s has 32bits Android OS though the CPU is 64bit](
https://community.infiniteflight.com/t/i-cannot-download-if-because-its-not-compatible/710435/4). Also, Android has [different definitions for `RTLD_*` for 32bits](https://android.googlesource.com/platform/bionic/+/refs/heads/main/libc/include/dlfcn.h).

[Even though I used C's `RTLD_*`, another crash happened](https://github.com/hajimehoshi/ebiten/issues/3052#issuecomment-2261184838). I am not sure when this happened. Maybe loading a symbol?

See also https://github.com/hajimehoshi/ebiten/issues/3052

**Comment by TotallyGamerJet** [comment]
This is such a strange case where it's a 64Bit CPU but a 32bit OS.

**Comment by hajimehoshi** [comment]
Indeed...
