### ISSUE TITLE
test fails with Go 1.15 on amd64 and purego 6ed67cd5f570b9c0d5710dfced2b1e77ad92ca1b

### ISSUE THREAD

**Issue by hajimehoshi** [ebitengine/purego#27]
```
go1.15.15 run -tags=example ./examples/audio
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4176b9e]

goroutine 17 [running, locked to thread]:
github.com/ebitengine/purego.callbackWrap(0xc000070000)
        /Users/hajimehoshi/go/pkg/mod/github.com/ebitengine/purego@v0.0.0-20220829171928-6ed67cd5f570/syscall_darwin.go:123 +0x17e
github.com/ebitengine/purego.callbackWrapPicker(0xc000070000, 0x4176f80)
        /Users/hajimehoshi/go/pkg/mod/github.com/ebitengine/purego@v0.0.0-20220829171928-6ed67cd5f570/syscall_darwin.go:106 +0x2b
exit status 2
```

/CC @TotallyGamerJet Please take a look... Thanks,

**Comment by hajimehoshi** [comment]
Go 1.16 worked as expected.

**Comment by hajimehoshi** [comment]
Note: Oto itself cannot be tested with Go 1.15 due to the `retract` section in `go.mod` unfortunately.

**Comment by hajimehoshi** [comment]
Testing with Go 1.15 still fails:

```
$ go1.15.15 test ./...
?       github.com/ebitengine/purego    [no test files]
?       github.com/ebitengine/purego/internal/fakecgo   [no test files]
?       github.com/ebitengine/purego/internal/strings   [no test files]
--- FAIL: ExampleAllocateClassPair (0.00s)
panic: runtime error: index out of range [4938557769273084744] with length 2000 [recovered]
        panic: runtime error: index out of range [4938557769273084744] with length 2000

goroutine 1 [running]:
testing.(*InternalExample).processRunResult(0xc00009dd28, 0x0, 0x0, 0x1bb2f, 0x113f960, 0xc000018420, 0x10144d4)
        /Users/hajimehoshi/sdk/go1.15.15/src/testing/example.go:89 +0x648
testing.runExample.func2(0xc0bb5db78fb6db90, 0xdc7fc, 0x1237440, 0xc000010050, 0xc000010018, 0xc000072240, 0xc000051d28, 0xc00009dd58)
        /Users/hajimehoshi/sdk/go1.15.15/src/testing/run_example.go:58 +0x10d
panic(0x113f960, 0xc000018420)
        /Users/hajimehoshi/sdk/go1.15.15/src/runtime/panic.go:969 +0x1b9
github.com/ebitengine/purego.callbackWrap(0x101813e)
        /Users/hajimehoshi/purego/syscall_darwin.go:116 +0x50f
github.com/ebitengine/purego.callbackWrapPicker(0x101813e, 0x110fba0)
        /Users/hajimehoshi/purego/syscall_darwin.go:106 +0x2b
github.com/ebitengine/purego.syscall_syscall9X(0x7ff80afe3400, 0x600000010030, 0x7ff825565129, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/hajimehoshi/purego/syscall_darwin.go:20 +0x128
github.com/ebitengine/purego.SyscallN(0x7ff80afe3400, 0xc00001a1e0, 0x2, 0x2, 0x0, 0xc00001a1e0, 0x2)
        /Users/hajimehoshi/purego/syscall.go:37 +0x11e
github.com/ebitengine/purego/objc.ID.Send(0x600000010030, 0x7ff825565129, 0x0, 0x0, 0x0, 0x0)
        /Users/hajimehoshi/purego/objc/objc_runtime_darwin.go:52 +0xb7
github.com/ebitengine/purego/objc_test.ExampleAllocateClassPair()
        /Users/hajimehoshi/purego/objc/objc_runtime_darwin_test.go:22 +0x1b3
testing.runExample(0x1152cf4, 0x18, 0x11589c8, 0x11503f1, 0xd, 0x0, 0x0)
        /Users/hajimehoshi/sdk/go1.15.15/src/testing/run_example.go:62 +0x209
testing.runExamples(0xc00009ded0, 0x1233f80, 0x4, 0x4, 0xc0bb5e4d8fb45ed8)
        /Users/hajimehoshi/sdk/go1.15.15/src/testing/example.go:44 +0x1af
testing.(*M).Run(0xc00011a000, 0x0)
        /Users/hajimehoshi/sdk/go1.15.15/src/testing/testing.go:1346 +0x273
main.main()
        _testmain.go:51 +0x138
FAIL    github.com/ebitengine/purego/objc       0.261s
FAIL
```

**Comment by TotallyGamerJet** [comment]
Are my build tags wrong in stackcc_darwin.go?

**Comment by TotallyGamerJet** [comment]
For Go 1.15 it should be the `const stackCallingConvention = true`

**Comment by hajimehoshi** [comment]
Apparently `stackcc_darwin.go` was chosen with Go 1.15 as expected.

**Comment by TotallyGamerJet** [comment]
Strange. This really makes me wish that we could use <ABIInternal> :( 

I don't have an amd64 machine on hand to test 1.15. It appears that 1.15 changed the calling convention unannounced.

**Comment by TotallyGamerJet** [comment]
These are the changes for [Go 1.15 ](https://go.dev/doc/go1.15). I don't think any of this should affect how purego chooses where the argument is.
> Package unsafe's [safety rules](https://go.dev/pkg/unsafe/#Pointer) allow converting an unsafe.Pointer into uintptr when calling certain functions. Previously, in some cases, the compiler allowed multiple chained conversions (for example, syscall.Syscall(…, uintptr(uintptr(ptr)), …)). The compiler now requires exactly one conversion. Code that used multiple conversions should be updated to satisfy the safety rules.
> 
> Go 1.15 reduces typical binary sizes by around 5% compared to Go 1.14 by eliminating certain types of GC metadata and more aggressively eliminating unused type metadata.
> 
> The toolchain now mitigates [Intel CPU erratum SKX102](https://www.intel.com/content/www/us/en/support/articles/000055650/processors.html) on GOARCH=amd64 by aligning functions to 32 byte boundaries and padding jump instructions. While this padding increases binary sizes, this is more than made up for by the binary size improvements mentioned above.
> 
> Go 1.15 adds a -spectre flag to both the compiler and the assembler, to allow enabling Spectre mitigations. These should almost never be needed and are provided mainly as a “defense in depth” mechanism. See the [Spectre wiki page](https://github.com/golang/go/wiki/Spectre) for details.
> 
> The compiler now rejects //go: compiler directives that have no meaning for the declaration they are applied to with a "misplaced compiler directive" error. Such misapplied directives were broken before, but were silently ignored by the compiler.
> 
> The compiler's -json optimization logging now reports large (>= 128 byte) copies and includes explanations of escape analysis decisions.

**Comment by TotallyGamerJet** [comment]
If we stop supporting Go 1.15 that would bump up Oto and Ebitengine too, correct? What are the downsides to bumping the version? How about the benefits?

I can definitely look into the cost of supporting Go 1.15. My hunch is that it shouldn't be too hard but currently I do not have an amd64 machine to test on.

Do you want to rollback Oto for now? Purego I think is okay to keep since it's barely used and only Go 1.15 is broken. I'll also close [ebitengine#2280](https://github.com/hajimehoshi/ebiten/pull/2280)

**Comment by hajimehoshi** [comment]
> If we stop supporting Go 1.15 that would bump up Oto and Ebitengine too, correct? What are the downsides to bumping the version? How about the benefits?

Correct. I wanted to support Go 1.15 since Debian bullseye's default version is Go 1.15. This is the rule I used but there is no strong reason to stick to this rule so strongly.

With Go 1.16, I will be able to use `go:embed`, `GOOS=ios`, and so on. So there are a lot of benefits. The cons is that Debian users would need to Go not by `apt`.

> I can definitely look into the cost of supporting Go 1.15. My hunch is that it shouldn't be too hard but currently I do not have an amd64 machine to test on.

Sure, thank you for tackling this issue!

> Do you want to rollback Oto for now? Purego I think is okay to keep since it's barely used and only Go 1.15 is broken. I'll also close https://github.com/hajimehoshi/ebiten/pull/2280

Sure, I'll rollback the latest for Oto later soon.

I appreciate your hard work!

**Comment by TotallyGamerJet** [comment]
I'm going to be dumping a lot of things for my reference so just ignore it all.

So it seems like cgocallback changed signatures from 1.15 to 1.16. This happened in [golang/go#30c1887](https://github.com/golang/go/commit/30c18878730434027dbefd343aad74963a1fdc48).

It used to be `cgocallback(fn, frame unsafe.Pointer, framesize, ctxt uintptr)`

but as of 1.16 it is `cgocallback(fn, frame unsafe.Pointer, ctxt uintptr)`.

**Comment by TotallyGamerJet** [comment]
It does not appear reasonable to support Go 1.15. It will require large portions of the purego runtime to be copied since the way 1.15 and 1.16+ handle callbacks is quite different. Specifically, 1.15 gets the callback object from the struct in assembly [here](https://github.com/golang/go/blob/404899f6b56800c1d8e0521fc9ce0c856e459d94/src/runtime/sys_windows_amd64.s#L307) and then calls the function directly with the exact frame [here](https://github.com/golang/go/blob/404899f6b56800c1d8e0521fc9ce0c856e459d94/src/runtime/asm_amd64.s#L503). The current, implementation uses the same struct layout for all callbacks and has reflect handle the dispatch call. 

So to break things down:
* 1.15 calls the callback directly from assembly
* 1.16+ jumps into Go code that determines which callback to do then calls it with reflect

These are large divergence that if we did include would likely be safe to do since 1.15 can't retroactively change its runtime but doing so would muddy up the code greatly for future versions.

**Comment by hajimehoshi** [comment]
I see...

Would it be possibe to create a 'fake purego' for Go 1.15, that actually uses the same interface but uses Cgo?

**Comment by TotallyGamerJet** [comment]
Uhm… I’m not sure. I’ll ponder on this thought

**Comment by hajimehoshi** [comment]
Thanks. If it is burden to you, I'm fine to give up supporting Go 1.15. As I have already said, supporting Go 1.15 is just a nice-to-have to me.
