### ISSUE TITLE
Generic APIs are needed for multiple platforms (or documentation of differences with examples)

### ISSUE THREAD

**Issue by texadactyl** [ebitengine/purego#273]
### Operating System

- [X] Windows
- [X] macOS
- [X] Linux
- [X] FreeBSD
- [X] Android
- [X] iOS

### What feature would you like to be added?

I am in agreement with the points made by both @RomainMuller and @platypusguy in PR https://github.com/ebitengine/purego/pull/192. APIs should not burden the user with O/S specifics wherever possible. The precise API names are not so important as long as they are universal.

However, at least, the project documentation needs an update.

Reference: https://pkg.go.dev/github.com/ebitengine/purego

"Supported Platforms" states that the APIs are supported on the listed platforms with the exception of a ARM32 and Windows-32 environments. However, the "Example" states that the APIs only work on POSIX systems contradicts the previous documentation sections.

It would be helpful if an equivalent documentation example for Windows was provided.  Also, under each API where Windows is not currently supported (E.g. Dlopen), depict the equivalent operation for Windows. Then, users authoring multiplatform projects would have some guidance without having to engage in significant trial-and-error activity.

### Why is this needed?

My goal is to be able to open and use a Java library Windows, Linux, Unix, and MacOS on 64-bit hardware platforms. I'll take care with providing the full paths. The dlfcn concept & code of @RomainMuller will be useful to me in modifying my own work.

**Comment by hajimehoshi** [comment]
Adding more explanation to the 'Example' section is fine. Thoughts? @TotallyGamerJet
