### ISSUE TITLE
The sign of the returned int value is inverted

### ISSUE THREAD

**Issue by johejo** [ebitengine/purego#279]
### PureGo Version

v0.8.0-alpha.5.0.20240903150804-6580f25cf0bb

### Operating System

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] Android
- [ ] iOS

### Go Version (`go version`)

go version go1.23.0 linux/amd64

### What steps will reproduce the problem?

```c
#include <stdio.h>

int test(void) { return (int)-(1 << 17); }

int main(void) {
  printf("%d", test());
  return 0;
}
```

```bash
# standalone
cc test.c -o test
```

```
$ ./test
-131072
```

expected

```bash
# shared object for purego
cc -shared -o libtest.so -fPIC test.c
```

```go
package main

/*
int test(void) { return (int)-(1 << 17); }
*/
import "C"

import (
	"fmt"
	"log"
	"path/filepath"

	"github.com/ebitengine/purego"
)

func main() {
	so, err := filepath.Abs("./libtest.so")
	if err != nil {
		log.Fatal(err)
	}
	libtest, err := purego.Dlopen(so, purego.RTLD_GLOBAL|purego.RTLD_NOW)
	if err != nil {
		log.Fatal(err)
	}

	var test func() int
	purego.RegisterLibFunc(&test, libtest, "test")

	fmt.Println("purego", test())

	fmt.Println("cgo", int(C.test()))

	fmt.Println("go", int(-(1 << 17)))
}
```

```
$ go run ./main.go
purego 131072
cgo -131072
go -131072
```

### What is the expected result?

Get -131072 in all cases

### What happens instead?

Only in the case of purego is the sign reversed.

### Anything else you feel useful to add?

I noticed this issue when trying to call `ZSTD_minCLevel` using purego.
https://github.com/facebook/zstd/blob/794ea1b0afca0f020f4e57b6732332231fb23c70/lib/zstd.h#L241
https://github.com/facebook/zstd/blob/794ea1b0afca0f020f4e57b6732332231fb23c70/lib/compress/zstd_compress.c#L6987

**Comment by TotallyGamerJet** [comment]
Can you try using `int32` in the purego example. `int` in C is often 32bit and `int` in Go on 64Bit Systems is 64bits

**Comment by johejo** [comment]
Thank you.

**Comment by TotallyGamerJet** [comment]
I’m glad that worked
