### ISSUE TITLE
internal/fakecgo: add build tags

### ISSUE THREAD

**Issue by hajimehoshi** [ebitengine/purego#28]
Now building `internal/fakecgo` for Windows fails since `internal/fakecgo` cannot be built for Windows.

```
$ env GOOS=windows GOARCH=amd64 go build -v ./...
github.com/ebitengine/purego/internal/fakecgo
# github.com/ebitengine/purego/internal/fakecgo
internal/fakecgo/go_util.go:29:2: undefined: _cgo_sys_thread_start
```

This is a little inconvenient since I cannot use `./...` for Windows. Would it be fine to add `darwin` for the `fakecgo` package?

**Comment by TotallyGamerJet** [comment]
I think this is fine.
