### ISSUE TITLE
internal/abi/abi_arm64.h Not included when vendoring dependencies

### ISSUE THREAD

**Issue by mechanical-lich** [ebitengine/purego#31]
I noticed this issue when upgrading Ebiten from 2.3.8 to 2.4.0, however this was the dependency throwing the error.  So I hope this is the right place to report this. 
Error: `# github.com/ebitengine/purego
vendor/github.com/ebitengine/purego/sys_darwin_arm64.s:8: #include: open /Users/<redacted>/sdk/go1.19/pkg/include/internal/abi/abi_arm64.h: no such file or directory`

Digging further I found that the folder `/internal/abi/` didn't exist in my vendored copy but `strings` and `fakecgo` did.  Which led me to [this comment](https://github.com/goccy/go-graphviz/issues/28#issuecomment-674405467) that mentions that there needs to be at least one .go file present in a directory in order for all the files to be included during vendoring.    I made sure it wasn't a fluke by deleting the vendor folder and starting over but the results were consistent.

There is a work around, I cloned the repo and manually copied it to the vendor folder and the issue resolved (until I vendor again)

**Comment by hajimehoshi** [comment]
I'm not familiar with vendoring, but would putting a dummy Go file in `internal/abi` solve this vendoring issue?

/CC @TotallyGamerJet

**Comment by hajimehoshi** [comment]
https://github.com/goccy/go-graphviz/pull/37/files

Hm, I see. Do we need a `required` build tag for this?

**Comment by hajimehoshi** [comment]
I've upated purego.

I'll update Oto and Ebitengine and then close this issue.

**Comment by hajimehoshi** [comment]
Until v2.4.2 is released, please try:

```
go get github.com/hajimehoshi/ebiten/v2@557bef998d148e4e19da0a70c1106c206aff0cef
```

Thanks,

**Comment by mechanical-lich** [comment]
Sorry for the late response!   I really appreciate you looking into this and thanks for your help!
