### ISSUE TITLE
Drop 1.15 Support

### ISSUE THREAD

**Issue by TotallyGamerJet** [ebitengine/purego#43]
This is not an issue that should be addressed now but exists solely to list the pros and cons of dropping support for 1.15.

Pros:
* It has caused many issues (#27, & #25 ) and required fixes that make the code more complicated (#34)
* It would allow us to close #37 which doesn't have a fix yet
* It would put us in line with [gomobile](https://cs.opensource.google/go/x/mobile/+/master:go.mod) support 
* Linux support would be easier (#38)
* All the features of [Go 1.16](https://go.dev/doc/go1.16) which includes `go:embed` &`GOOS=iOS`
* Close [ebitengine#2281](https://github.com/hajimehoshi/ebiten/issues/2281) as [gomobile](https://pkg.go.dev/golang.org/x/mobile/cmd/gomobile)'s lowest version is 1.13

Cons:
* Debian's default version is 1.15
* This effects both big projects (Oto and Ebitengine)

**Comment by hajimehoshi** [comment]
I agree with this pros and cons.

**Comment by hajimehoshi** [comment]
> This effects both big projects (Oto and Ebitengine)

Oto's go.mod specifies go1.16 for a `retract` section, but doesn't drop Go 1.15 yet.

For Ebitengines, there are some issues we can solve:

* https://github.com/hajimehoshi/ebiten/issues/1415
* https://github.com/hajimehoshi/ebiten/issues/1770
* https://github.com/hajimehoshi/ebiten/issues/1258
* https://github.com/hajimehoshi/ebiten/issues/2276

**Comment by hajimehoshi** [comment]
As the Ebitengine side, I can accept dropping Go 1.15 now. Since [the stable Ebitengine v2.4 was released two weeks ago](https://ebiten.org/blog/v2.4.0.html) and the unstable v2.5 started, it is a good timing to change supporting platforms. Note that Ebitengine's stable version is released twice every year, like what Go does.

**Comment by TotallyGamerJet** [comment]
So you want to move forward with dropping 1.15 support? Debian bookworm likely won't come out until after 2.5 for Ebitengine is released

**Comment by hajimehoshi** [comment]
> So you want to move forward with dropping 1.15 support? Debian bookworm likely won't come out until after 2.5 for Ebitengine is released

I don't say I eager to drop 1.15. My opinion is I'm fine with dropping it if necessary.

From the current situation you are struggling with, I vote to drop Go 1.15!

**Comment by hajimehoshi** [comment]
@TotallyGamerJet If you vote to drop Go 1.15, let's do so!

**Comment by TotallyGamerJet** [comment]
I am definitely in favor of dropping 1.15 support.

**Comment by TotallyGamerJet** [comment]
Yep you are good to go!

**Comment by hajimehoshi** [comment]
Done :-)

**Comment by hajimehoshi** [comment]
* The `main` branch has v0.2.0-alpha or other alpha version tags
* we will commit changes to the `main` branch first
* If the change is a bug fix, back-port to stable branches like `0.1`

This is the same rule as Ebitengine.
