### ISSUE TITLE
RTLD_DEFAULT has wrong value

### ISSUE THREAD

**Issue by TotallyGamerJet** [ebitengine/purego#52]
According to [opensource.apple.com](https://opensource.apple.com/source/dyld/dyld-360.14/include/dlfcn.h.auto.html) `RTLD_DEFAULT` is defined as `#define	RTLD_DEFAULT	((void *) -2)`. In purego I wrote `const RTLD_DEFAULT = ^uintptr(1)` which is not the same binary representation. 

This is a bug in version 0.1.0 and should be corrected to something like `const RTLD_DEFAULT   = uintptr(0x8000000000000002)` .

Secondly, I think we should remove this constant from purego 0.2.0 since it is not used in purego, Oto or Ebitengine and is darwin specific. See the [Unix specification](https://pubs.opengroup.org/onlinepubs/7908799/xsh/dlfcn.h.html).

**Comment by hajimehoshi** [comment]
> const RTLD_DEFAULT = uintptr(0x8000000000000002) .

Doesn't this depend on the size of the pointer? I thought `^uintptr(1)` seemed correct.

https://go.dev/play/p/cITG1_TGLgY

> Secondly, I think we should remove this constant from purego 0.2.0 since it is not used in purego, Oto or Ebitengine and is darwin specific. See the [Unix specification](https://pubs.opengroup.org/onlinepubs/7908799/xsh/dlfcn.h.html).

It's OK to remove this.

**Comment by TotallyGamerJet** [comment]
Oh you're right. They are the same.
> It's OK to remove this.

I'll create a PR
