### ISSUE TITLE
Back Port to 0.1

### ISSUE THREAD

**Issue by TotallyGamerJet** [ebitengine/purego#64]
Should we backport this commit to 1.0 since it's the only tagged version and this bug can cause issues? https://github.com/ebitengine/purego/commit/382f4c69b85482e885511dd001710fd145469a76

**Comment by hajimehoshi** [comment]
You mean `0.1`?

Yes, let's backport this. Ebitengine 2.4 fortunately doesn't have the issue, so this is not urgent.

**Comment by hajimehoshi** [comment]
Thanks!
