### ISSUE TITLE
.github/workflows: add test for Go 1.20

### ISSUE THREAD

**Issue by TotallyGamerJet** [ebitengine/purego#74]
When Go 1.20 is released add a test that includes `CGO_ENABLED=0` and `-race`.

See #71 for more information.

**Comment by hajimehoshi** [comment]
At least we can add `CGO_ENABLED=0` and `-race` for the current versions, right?

**Comment by TotallyGamerJet** [comment]
That won't compile since `-race` requires Cgo.

**Comment by hajimehoshi** [comment]
You are right!

**Comment by hajimehoshi** [comment]
We can now add tests by specifying '1.20.0-rc.1' in the yaml.

https://twitter.com/golang/status/1600612450197446675

**Comment by TotallyGamerJet** [comment]
Please feel free to make that PR!
