### ISSUE TITLE
tag `v0.2.0-alpha.1`

### ISSUE THREAD

**Issue by hajimehoshi** [ebitengine/purego#94]
The latest tag is now `v0.2.0-alpha` but this is outdated. As there has not been drastic changes in the main branch, I'd like to tag `v0.2.0-alpha.1` for the latest commit.

@TotallyGamerJet, what do you think?

BTW, I plan to make 0.2 branch including non-alpha v0.2.x versions when Ebitengine v2.5 is released.

**Comment by TotallyGamerJet** [comment]
I think that's a good idea!

**Comment by hajimehoshi** [comment]
Thanks, done!
